import 'dart:collection';
import 'dart:convert';

import 'bengali_transliteration.dart';

class LanguageUtils {
  static final Map<String, String> transliterateMap = {
    'œ': 'oe',
    'ª': 'a',
    'º': 'o',
    '«': '\"',
    '»': '\"',
    // Scandinavian characters
    'Æ': 'Ae',
    'æ': 'ae',
    'Ø': 'Oe',
    'ø': 'oe',
    'Å': 'Aa',
    'å': 'aa',
    // German characters
    'ä': 'ae',
    'ö': 'oe',
    'ü': 'ue',
    'Ä': 'Ae',
    'Ö': 'Oe',
    'Ü': 'Üe',
    'ß': 'ss',
    'ẞ': 'SS',
    // French characters
    'à': 'a',
    'â': 'a',
    'é': 'e',
    'è': 'e',
    'ê': 'e',
    'ë': 'e',
    'ù': 'u',
    'ÿ': 'y',
    'ç': 'c',
    // Russian characters
    'а': 'a',
    'б': 'b',
    'в': 'v',
    'г': 'g',
    'д': 'd',
    'е': 'e',
    'ё': 'jo',
    'ж': 'zh',
    'з': 'z',
    'и': 'i',
    'й': 'jj',
    'к': 'k',
    'л': 'l',
    'м': 'm',
    'н': 'n',
    'о': 'o',
    'п': 'p',
    'р': 'r',
    'с': 's',
    'т': 't',
    'у': 'u',
    'ф': 'f',
    'х': 'kh',
    'ц': 'c',
    'ч': 'ch',
    'ш': 'sh',
    'щ': 'shh',
    'ъ': '\"',
    'ы': 'y',
    'ь': '\'',
    'э': 'eh',
    'ю': 'ju',
    'я': 'ja',
    // Hebrew characters
    'א': 'a',
    'ב': 'b',
    'ג': 'g',
    'ד': 'd',
    'ה': 'h',
    'ו': 'u',
    'ז': 'z',
    'ח': 'kh',
    'ט': 't',
    'י': 'y',
    'כ': 'c',
    'ל': 'l',
    'מ': 'm',
    'נ': 'n',
    'ס': 's',
    'ע': '\'',
    'פ': 'p',
    'צ': 'ts',
    'ק': 'k',
    'ר': 'r',
    'ש': 'sh',
    'ת': 'th',
    'ף': 'f',
    'ץ': 'ts',
    'ך': 'ch',
    'ם': 'm',
    'ן': 'n',
    // Greek characters
    'α': 'a',
    'ά': 'a',
    'β': 'v',
    'γ': 'g',
    'δ': 'd',
    'ε': 'e',
    'έ': 'e',
    'ζ': 'z',
    'η': 'i',
    'ή': 'i',
    'θ': 'th',
    'ι': 'i',
    'ί': 'i',
    'ϊ': 'i',
    'ΐ': 'i',
    'κ': 'k',
    'λ': 'l',
    'μ': 'm',
    'ν': 'n',
    'ξ': 'ks',
    'ο': 'o',
    'ό': 'o',
    'π': 'p',
    'ρ': 'r',
    'σ': 's',
    'ς': 's',
    'τ': 't',
    'υ': 'y',
    'ύ': 'y',
    'ϋ': 'y',
    'ΰ': 'y',
    'φ': 'f',
    'χ': 'ch',
    'ψ': 'ps',
    'ω': 'o',
    'ώ': 'o',
    'Α': 'A',
    'Ά': 'A',
    'Β': 'B',
    'Γ': 'G',
    'Δ': 'D',
    'Ε': 'E',
    'Έ': 'E',
    'Ζ': 'Z',
    'Η': 'I',
    'Ή': 'I',
    'Θ': 'TH',
    'Ι': 'I',
    'Ί': 'I',
    'Ϊ': 'I',
    'Κ': 'K',
    'Λ': 'L',
    'Μ': 'M',
    'Ν': 'N',
    'Ξ': 'KS',
    'Ο': 'O',
    'Ό': 'O',
    'Π': 'P',
    'Ρ': 'R',
    'Σ': 'S',
    'Τ': 'T',
    'Υ': 'Y',
    'Ύ': 'Y',
    'Ϋ': 'Y',
    'Φ': 'F',
    'Χ': 'CH',
    'Ψ': 'PS',
    'Ω': 'O',
    'Ώ': 'O',
    // Ukrainian characters
    'ґ': 'gh',
    'є': 'je',
    'і': 'i',
    'ї': 'ji',
    'Ґ': 'GH',
    'Є': 'JE',
    'І': 'I',
    'Ї': 'JI',
    // Arabic characters
    'ا': 'a',
    'ب': 'b',
    'ت': 't',
    'ث': 'th',
    'ج': 'j',
    'ح': '7',
    'خ': '5',
    'د': 'd',
    'ذ': 'th',
    'ر': 'r',
    'ز': 'z',
    'س': 's',
    'ش': 'sh',
    'ص': '9',
    'ض': '9\'',
    'ط': '6',
    'ظ': '6\'',
    'ع': '3',
    'غ': '3\'',
    'ف': 'f',
    'ق': 'q',
    'ك': 'k',
    'ل': 'l',
    'م': 'm',
    'ن': 'n',
    'ه': 'h',
    'و': 'w',
    'ي': 'y',
    'ى': 'a',
    'ﺓ': '',
    'آ': '2',
    'ئ': '2',
    'إ': '2',
    'ؤ': '2',
    'أ': '2',
    'ء': '2',
    '٠': '0',
    '١': '1',
    '٢': '2',
    '٣': '3',
    '٤': '4',
    '٥': '5',
    '٦': '6',
    '٧': '7',
    '٨': '8',
    '٩': '9',
    '»': '<',
    '«': '>',
    'ِ': 'e',
    'َ': 'a',
    'ُ': 'o',
    'ّ': '',
    // Polish
    'Ł': 'L',
    'ł': 'l',
    // Lithuanian
    'ą': 'a',
    'č': 'c',
    'ę': 'e',
    'ė': 'e',
    'į': 'i',
    'š': 's',
    'ų': 'u',
    'ū': 'u',
    'ž': 'z',
    // Estonian
    'ä': 'a',
    'Ä': 'A',
    'ö': 'o',
    'õ': 'o',
    'Ö': 'O',
    'Õ': 'O',
    'ü': 'u',
    'Ü': 'U',
    // Icelandic
    'Þ': 'Th',
    'þ': 'th',
    'Ð': 'D',
    'ð': 'd',
    // Czech
    'ř': 'r',
    'ě': 'e',
    'ý': 'y',
    'á': 'a',
    'í': 'i',
    'é': 'e',
    'ó': 'o',
    'ú': 'u',
    'ů': 'u',
    'ď': 'd',
    'ť': 't',
    'ň': 'n',
  };

  static String transliterate(String txt) {
    if (txt == null || txt.isEmpty) {
      return txt;
    }

    String message = '';

    // Simple, char-by-char transliteration.
    for (int i = 0; i < txt.length; i++) {
      String c = txt[i];
      message += transliterateChar(c);
    }

    // More complex transliteration for specific languages.
    // message = BengaliLanguageUtils.transliterate(message);
    // message = KoreanLanguageUtils.transliterate(message);

    return flattenToAscii(message);
  }

  static String transliterateChar(String c) {
    if (transliterateMap.containsKey(c.toLowerCase())) {
      String replace = transliterateMap[c.toLowerCase()]!;
      if (c.toLowerCase() != c) {
        return replace[0].toUpperCase() + replace.substring(1);
      }
      return replace;
    }
    return c;
  }

  static String flattenToAscii(String string) {
    return string;
  }
}
